"""empty message

Revision ID: 42988f64f904
Revises: 58cb19222710
Create Date: 2024-01-07 16:44:23.402935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42988f64f904'
down_revision = '58cb19222710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_team_league_id', 'league', ['league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_league_id', type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###
