"""Add league_id and named constraints to Team model

Revision ID: 9cfbf0ab2fb7
Revises: b16b5581873a
Create Date: 2024-11-25 14:09:37.500191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfbf0ab2fb7'
down_revision = 'b16b5581873a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('founded_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_team_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_name', type_='unique')
        batch_op.alter_column('logo_url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('founded_year')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
