"""Add is_correct and confidence fields to Analysis model

Revision ID: c66d2be45182
Revises: ab40582670e5
Create Date: 2024-11-25 13:35:35.100101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d2be45182'
down_revision = 'ab40582670e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('analysis_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_column('analysis_type')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
